TaskCategory/Models/CategoryModel.cs
using System;
namespace TaskCategory.Models
{
	public class CategoryModel
	{
        public int Id { get; set; }

		public string Name { get; set; }
	}
}

TaskCategory/Models/ErrorViewModel.cs
namespace TaskCategory.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

TaskCategory/Models/ProductModel.cs
using System;
namespace TaskCategory.Models
{
	public class ProductModel
	{
        public int Id { get; set; }

        public int CategoryId { get; set; }

        public string Name { get; set; }

        public bool IsNew { get; set; }

        public decimal Price { get; set; }
    }
}

TaskCategory/Models/Repository.cs
using System;
using System.Collections.Generic;
using TaskCategory.Data.Context;
using TaskCategory.Entity.Entities;

namespace TaskCategory.Models
{
	public class Repository
	{
		private static List<CategoryModel> categories = null;

		static Repository()
		{
			categories = new List<CategoryModel>()
			{
				new CategoryModel {Id = 1,Name = "Bilgisayar"},
                new CategoryModel {Id = 2,Name = "Telefon"},
                new CategoryModel {Id = 3,Name = "Tablet"},
                new CategoryModel {Id = 4,Name = "Kulaklık"},
            };
		}

		public List<CategoryModel> GetcategoryModels()
		{
			return categories;
		}
    }
}

TaskCategory/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TaskCategory.Data.Context;
using TaskCategory.Entity.Entities;

namespace TaskCategory.Controllers
{
    public class CategoryController : Controller
    {
        private readonly AppDbContext _db;

        public CategoryController(AppDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            List<Product> objListCategory = _db.Products.ToList();
            return View(objListCategory);
        }
    }
}

TaskCategory/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using TaskCategory.Models;

namespace TaskCategory.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

TaskCategory/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using TaskCategory.Data.Context;
using TaskCategory.Entity.Entities;

namespace TaskCategory.Controllers
{
    public class ProductController : Controller
    {
        private readonly AppDbContext _db;

        public ProductController(AppDbContext db)
        {
            _db = db;
        }

        [Route("Product/Index/{id}")]
        public IActionResult Index(int id)
        {
            List<Product> objListProduct = _db.Products.Where(x => x.CategoryId == id && x.IsNew).ToList();
            return View(objListProduct);
        }

        [Route("Product/IndexProductDetail/{id}")]
        public IActionResult IndexProductDetail(int id)
        {
            List<Product> objListProduct = _db.Products.Where(x => x.Id == id).ToList();
            return View(objListProduct);
        }
    }
}

TaskCategory/Controllers/ProductDetailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using TaskCategory.Data.Context;
using TaskCategory.Entity.Entities;

namespace TaskCategory.Controllers
{
    public class ProductDetailController : Controller
    {
        private readonly AppDbContext _db;

        public ProductDetailController(AppDbContext db)
        {
            _db = db;
        }

        [Route("ProductDetail/Index/{id}")]
        public IActionResult Index(int id)
        {
            List<Product> objListProduct = _db.Products.Where(x => x.Id == id).ToList();
            return View(objListProduct);
        }
    }
}

TaskCategory/Views/Category/Index.cshtml
@model IEnumerable<TaskCategory.Entity.Entities.Product>


    <br />
    <br />

<div class="border p-4 bg-white">
    <div class="row">
        <div class="text-info"> Ürün Listesi</div>
    </div>
</div>

<br />

<div>
    @if (Model.Count() > 0)
        {
            <table class="table table-stripped border">
                <tr class="table-secondary">
                    <th>Ürün Adı</th>
                </tr>

                @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                               <a class="btn btn-primary text-white" asp-action="GoCategory4Product"
                                  asp-route-Id="@item.Id">@item.Name</a>
                            </td>
                        </tr>
                    }
            </table>

        }
        else
        {
            <p>Listelenecek veri bulunamadı...</p>
        }

</div>

TaskCategory/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="col-md-9">
    <h1 class="display-4">Hoşgeldiniz</h1>
    <p>Lütfen kategori seçiniz.</p>
</div>

TaskCategory/Views/Product/Index.cshtml
@model IEnumerable<TaskCategory.Entity.Entities.Product>

<br />
<a>ÜRÜN BİLGİSİ</a>
<br />
<br />
<div class="row">
    <div class="col-md-3">
        @if (Model.Count() > 0)
        {
            <table class="table table-stripped border">
                <tr class="table-secondary">
                    <th>Kategori Adı</th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            <a class="btn btn-primary text-white" asp-action="Index" asp-controller="ProductDetail"
                               asp-route-id="@item.Id">@item.Name</a>
                        </td>
                    </tr>
                }
            </table>

        }
        else
        {
            <p>Listelenecek veri bulunamadı...</p>
        }
    </div>
</div>

TaskCategory/Views/ProductDetail/Index.cshtml
@model IEnumerable<TaskCategory.Entity.Entities.Product>

@foreach (var item in Model)
{
    <div>
        <h3>Ürün Bilgileri</h3>
        <ul>
            <li><strong>Ürün Adı:</strong> @item.Name</li>
            <li><strong>Ürün Fiyatı:</strong> @item.Price.ToString("C")</li>
        </ul>
    </div>
}

TaskCategory/Views/Shared/_CategoryLayout.cshtml
@model IEnumerable<TaskCategory.Entity.Entities.Product>


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UTKU ÖZCAN</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TaskCategory.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        @Html.Partial("_navbar")
    </header>
    <br />
    <div class="row">
        <div class="col-md-3">
            @Html.Partial("_menu")
        </div>

        <div class="col-md-9">
            @RenderBody()
        </div>
    </div>

    <footer>
        @Html.Partial("_footer")
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TaskCategory/Views/Shared/_menu.cshtml
@{
    Repository _Repository = new Repository();
    var modelCategory = _Repository.GetcategoryModels();
}


<div class="list-group">

    @foreach (var item in modelCategory)
    {
        <a asp-action="Index" asp-controller="Product" asp-route-id="@item.Id"
           class="list-group-item list-group-item-action" style="margin-inline:5px;">@item.Name</a>
    }
</div>

TaskCategory/Views/Shared/_navbar.cshtml
<div class="navbar navbar-expand-sm bg-primary navbar-dark">
    <div class="container">
        <a sp-action="Product" asp-action="Index" class="navbar-brand">Utku Özcan</a>
        <ul class="navbar-nav">
            <li class="nav-item">
                <a sp-action="Home" asp-action="Index"class="nav-link">Login</a>
            </li>
        </ul>
    </div>
</div>